import type { Metadata } from 'next';
import { ABeeZee, Geist, Geist_Mono } from 'next/font/google';
import './shared/styles/globals.scss';
import Header from './shared/components/layout/Header/Header';
import Footer from './shared/components/layout/Footer/Footer';
import { FavoriteStoreProvider } from './core/providers/favoriteProvider';
import { BasketStoreProvider } from './core/providers/basketProvider';
import { DislikeStoreProvider } from './core/providers/dislikeProvider';
import { SortStoreProvider } from './core/providers/sortProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const abeezee = ABeeZee({
  weight: ['400'],
  style: ['normal'],
  variable: '--font-abeezee',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${geistSans.variable} ${geistMono.variable} ${abeezee.variable}`}>
        <DislikeStoreProvider>
          <FavoriteStoreProvider>
            {/* Все что внутри - имеет доступ к данным провайдера */}
            <BasketStoreProvider>
              <SortStoreProvider>
                <Header />
                {children}
                <Footer />
              </SortStoreProvider>
            </BasketStoreProvider>
          </FavoriteStoreProvider>
        </DislikeStoreProvider>
      </body>
    </html>
  );
}
