import type { Metadata } from 'next';
import { ABeeZee, Abel } from 'next/font/google';
import './globals.css';

const abeezeeRegular = ABeeZee({
  variable: '--font-abeezee-regular',
  weight: "400", 
  style: ['normal']
});

const abel = Abel({
  variable: '--font-abel',
  weight: "400", 
  style: ['normal']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${abeezeeRegular.variable} ${abel.variable}`}>{children}</body>
    </html>
  );
}
